name: FashionLiteracy
title: FashionLiteracy | A blog on Fashion Education
description: FashionLiteracy is a community of aspirants and professional of Fashion Industry
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email: info@fashionliteracy.com
disqus_username: fashion-literacy
show_hero: true
menu:
  - title: Home
    url: /
  - title: Write For Us
    url: /write-for-us
  - title: Blog
    url: /category/blog
  - title: Technology
    url: /category/technology
  - title: GD Topics
    url: /category/gdtopic
  - title: Jobs
    url: /category/jobs
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
