name: FashionLiteracy
title: FashionLiteracy | A blog on Fashion Education
description: FashionLiteracy is a community of aspirants and professional of Fashion Industry
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email: info@fashionliteracy.com
disqus_username: fashion-literacy
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
